### ISSUE TITLE
Blender freezing and crashing when trying to import json

### ISSUE THREAD

**Issue by MacDon510** [Kirpal/Keyboard-Layout-Editor-for-Blender#51] opened 2019-11-09 11:16 UTC
Blender completely freezes and crashes when trying to import json after updating to v.3.0 and Blender 2.80. Previously 2.79 was working just fine for me with the exception of arrow keys which is why I tried updating now it doesn't work at all. Please help thank you for your time.

**Comment by Kirpal** [comment] 2019-11-09 12:39
What are your specs? And please post a layout for which it crashes.

**Comment by MacDon510** [comment] 2019-11-09 23:10
http://www.keyboard-layout-editor.com/#/gists/aa453d8581843894eca39e5a826699b9

I use a surface pro 6 which is not that great but 2.79 was working just fine for me.

**Comment by Kirpal** [comment] 2019-11-12 02:16
I've been unable to reproduce.. Have you tried any other layouts? Do they cause crashes?

**Comment by shinjikun1011** [comment] 2019-11-12 14:05
Have gaming rig, unable to import at all into 2.8. Crashes every time. Also tried uninstalling blender completely and restarting. Installing and restarting etc. Json will not import, it will become not responding every time. I have tried 3 or 4 layouts.

**Comment by shinjikun1011** [comment] 2019-11-12 15:09
I was able to successfully import the render into 2.8 by making sure my video card was checked in preferences. Also on the right hand side of blender in scene I checked: cycles, supported, and gpu compute. This solved the freezing issue but not without traceback errors. Also arrows are now supported in the import but no other characters are supported (such as Hiragana). If you tell me how to find the traceback error information, I will send. Thank you for making this wonderful addon.

**Comment by Kirpal** [comment] 2019-11-12 16:21
The errors can be found by changing the Editor Type from '3D Viewport' to 'Info' (should be a dropdown on the top left of your viewport). The errors are selectable by just clicking them and hitting `ctrl+c`, or a screenshot would work well too. Thank you!

**Comment by strangest** [comment] 2019-11-20 04:07
Same here, but doesn't import successfully even with mentioned settings. Freezes on file selection menu, not on main screen, so unable to read Info output. Same results for presets or custom layouts.
In ~30 seconds memory used by Blender increases to ~10Gb, then Blender crashes.
Threadripper 1920x, GTX1060 6Gb, 32Gb RAM, win10.

**Comment by Kirpal** [comment] 2019-11-20 19:03
@strangest  Can you try running blender from the command line? It should print any logs/errors there so you can see them even when it crashes. I can't really do anything unless I can reproduce it or get the error messages. Thanks!

**Comment by strangest** [comment] 2019-11-21 02:26
lines of "removed 2/3 vertices" and "using fallback". then it stops for quite some time and throws an error.
```
Error   : Unrecognized Exception
Address : 0x00007FFBFCB6A839
Module  : C:\Windows\System32\KERNELBASE.dll
```

**Comment by GreenPigeon** [comment] 2019-11-23 01:52
it does the same for me whenever I try to open a json file too

**Comment by FakeDazon** [comment] 2020-01-16 18:11
Blender does the same for me, but even with checking my video card and setting it crashes upon import. Blender completely freezes my computer, and I have to restart it to get it to unfreeze.

**Comment by Raravin-Keebs** [comment] 2020-01-19 00:22
Was getting it on 2.8 as well tried rolling back to 2.79 and getting  Traceback call error most recent ascii

**Comment by Kirpal** [comment] 2020-02-26 20:00
Could you try again with the current master branch and see if you still have issues?

**Comment by StarrKiss** [comment] 2020-03-09 21:36
This happens to me too, I just tried it on Blender 2.82 on a system with an i7, 8700k

**Comment by DanielGGordon** [comment] 2020-03-25 01:40
I just downloaded 2.82a and yea this still happens. It just hangs when trying to import the json, but eventually finishes after 2-3 minutes.

**Comment by snagy** [comment] 2020-03-25 03:05
Can you make sure you fully uninstall the old plugin and download the new zip and install the plugin fresh from that?  I don't know another way to reliably update it.

**Comment by FakeDazon** [comment] 2020-04-11 00:43
I just installed the latest commit from the master branch, and it works as expected. It does take 1-2 minutes when importing the JSON, but that is likely due to the number of keys that were in the layout.

**Comment by MalishiDev** [comment] 2020-10-22 00:00
this is also happening to me on the LTS

**Closed** 2020-10-23 04:49 UTC
Labels: bug
