### ISSUE TITLE
Import option for KLE Raw Data (.json)

### ISSUE THREAD

**Issue by nopunin10did** [Kirpal/Keyboard-Layout-Editor-for-Blender#49] opened 2019-10-16 19:14 UTC
Windows 10, 64-bit.  Blender version 2.80.75.

I performed the installation steps and can currently see "Import-Export: KLE Raw JSON format (.json)" in my Add-ons menu.  It is checked, though it has a note about "upgrade to 2.8x required."

However, KLE Raw Data (.json) does not currently appear as an option in the File - Import menu.

**Comment by Kirpal** [comment] 2019-10-16 19:28
The addon hasn't been updated for 2.80 yet, please use 2.79 for now. Duplicate of #46

**Closed by Kirpal** 2019-10-16 19:28 UTC
